<a href="https://colab.research.google.com/github/DarshanBothra/PyTorch-Deep-Learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# !pip list
import torch as pt
import numpy as np

In [7]:
# 1-D Array
my_list1 = [
    1, 2, 3, 4, 5
]

# 2-D Array
my_list2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]



([1, 2, 3, 4, 5], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
np1 = np.random.rand(3) # 1-D numpy array

tensor_2d = pt.randn(3, 4) # 2-D Tensor
tensor_3d = pt.zeros(2, 3, 4) # 3-D Tensor

# Create tensor with numpy array
tensor_1d = pt.tensor(np1)

print(tensor_2d)
print(tensor_2d.dtype)
print(tensor_3d)
print(tensor_3d.dtype)
print(tensor_1d)
print(tensor_1d.dtype)


tensor([[-1.7845,  2.4506, -0.9552, -0.7598],
        [-0.6174, -2.4172, -0.3372,  0.1134],
        [-0.0067, -1.3505,  0.0676, -0.9357]])
torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32
tensor([0.5665, 0.2903, 0.9349], dtype=torch.float64)
torch.float64


In [25]:
my_torch = pt.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)

my_torch2 = pt.arange(10)
my_torch2 = my_torch2.reshape(2, -1) # -1 will take len(tensor)/2 elemnets automatically
my_torch2
my_torch3 = my_torch2.view(-1, 2)
my_torch4 = my_torch3.reshape(5, 2)
my_torch3.shape, my_torch4.shape

# Difference between reshape and view
# View will reshape the tensor without changing the memory allocation for the tensors!
# Reshape will reshape the tensor, it might change the memory allocation for the tensor though!

(torch.Size([5, 2]), torch.Size([5, 2]))

In [48]:
my_torch5 = pt.arange(10)
my_torch5
my_torch6 = my_torch5.view(2, 5)
my_torch5[1] = 4141
my_torch5
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [59]:
# Slicing

my_torch7 = pt.arange(10)

# Specific Item
print(my_torch7[7])
print()
# Slicing
my_torch8 = my_torch7.reshape(5, 2)
print(my_torch8)
print()
print(my_torch8[:3,1:])
print()


tensor(7)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

tensor([[1],
        [3],
        [5]])

